### ISSUE TITLE
Some kind of bug

### ISSUE THREAD

**Issue by dsomni** [declanvk/dancing-links#4]
Using your library to solve a sudoku, I have found the following bug. When I start you solver for sudoku 300080900000340000008005600500104070002009010003000040005001200000000000070008090 , the program crashed with such error: thread 'main' panicked at 'assertion failed: !column.is_covered', _C:\Users\User\.cargo\registry\src\github.com-1ecc6299db9ec823\dancing-links-0.2.0\src\grid.rs:397:9_ . I have no idea, why it occurs. If it is important, the above sudoku has an answer  -  351786924697342185428915637569134872742859316813267549935471268284693751176528493.

**Comment by declanvk** [comment]
Thanks for the report! I'll take a look

**Comment by declanvk** [comment]
I'm making slow progress on this in the `fix-regression` branch, will post a PR once I have a solution.

**Comment by declanvk** [comment]
@tyfkda has fixed this in #5

**Comment by declanvk** [comment]
Release cut https://github.com/declanvk/dancing-links/releases/tag/v0.3.0
